# Generated by Django 4.1.9 on 2024-04-02 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
