# Generated by Django 5.0.6 on 2024-05-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0004_asignaturas_delete_asginaturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='dirreccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='dirreccion',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha_envio',
            field=models.DateTimeField(),
        ),
    ]
