# Generated by Django 5.0.6 on 2024-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0008_citas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='dni_alumnos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='citas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
