# Generated by Django 5.0.6 on 2024-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0009_alter_citas_dni_alumnos_alter_citas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='examen',
            field=models.CharField(default='Evaluacion', max_length=50),
            preserve_default=False,
        ),
    ]
