# Generated by Django 5.0.6 on 2024-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0010_notas_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notas',
            name='dni_alumno',
            field=models.CharField(max_length=9),
        ),
    ]
