# Generated by Django 5.0.6 on 2024-06-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0012_remove_notas_id_alter_alumnos_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencias',
            old_name='num_faltas',
            new_name='faltas',
        ),
        migrations.RenameField(
            model_name='asistencias',
            old_name='num_retrasos',
            new_name='retrasos',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='faltas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faltas_alumno', to='Plazeduca.asistencias'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='retrasos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrasos_alumno', to='Plazeduca.asistencias'),
        ),
    ]
