# Generated by Django 5.0.6 on 2024-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0015_trabajos_id_alter_trabajos_dni_alumnos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trabajos',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
