# Generated by Django 5.0.6 on 2024-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0016_alter_trabajos_unique_together_alter_trabajos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='fecha_subida',
            field=models.DateField(),
        ),
    ]
