# Generated by Django 5.0.6 on 2024-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0017_alter_notas_fecha_subida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notificacion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('emisario', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField()),
            ],
        ),
    ]
