# Generated by Django 5.0.6 on 2024-06-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0018_notificaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='dni_profesor',
            new_name='emisor',
        ),
        migrations.RenameField(
            model_name='citas',
            old_name='dni_alumnos',
            new_name='receptor',
        ),
    ]
