# Generated by Django 5.0.6 on 2024-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0019_rename_dni_profesor_citas_emisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='faltas',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='retrasos',
        ),
        migrations.AddField(
            model_name='asistencias',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='dni_alumnos',
            field=models.CharField(max_length=9),
        ),
    ]
