# Generated by Django 5.0.6 on 2024-06-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plazeduca', '0020_remove_alumnos_faltas_remove_alumnos_retrasos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='faltas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnos',
            name='retrasos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
